image: gradle:latest

stages:
  - build
  - checkstyle

build-job:
  stage: build
  script:
    - echo "$CI_MERGE_REQUEST_DIFF_ID"
    - echo "$CI_SERVER_VERSION"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_COMMIT_SHA"
    - echo "$CI_COMMIT_AUTHOR"
    - echo "$CI_COMMIT_MESSAGE"
    - gradle assemble

  artifacts:
    when: on_failure
    paths:
      - $CI_PROJECT_DIR/*/build/reports/*

checkstyle-job:
  stage: checkstyle
  script:
    - gradle check
  artifacts:
    when: on_success
    paths:
      - $CI_PROJECT_DIR/*
